import type { EventArchetypeConfig } from '@/lib/planner/archetypes/types'

// TODO(archetype-pricing): The source matrix did not include ticket or minimum-spend
// ranges. These defaults are conservative planning ranges and should be reviewed with
// real Bay Area marketplace data after launch.
export const ARCHETYPES = [
  {
    key: 'networking_mixer',
    display_name: 'Networking mixer',
    aliases: [
      'mixer', 'happy hour', 'happyhour', 'networking', 'networking event',
      'networking mixer', 'after work drinks', 'cocktail hour',
      'professional mixer', 'founder mixer', 'startup mixer', 'start up mixer',
      'tech mixer', 'industry mixer', 'social mixer',
    ],
    adjacent_archetypes: ['community_meetup', 'day_party_brunch_party', 'panel_fireside'],
    description: 'Standing-room professional social with drinks and light networking.',
    preferred_venue_types: ['bar', 'lounge', 'rooftop', 'coworking_event_space'],
    capacity_range: [40, 150],
    capacity_ratio_min: 1.1,
    capacity_ratio_max: 1.6,
    required_amenities: ['standing_room', 'full_bar'],
    bonus_amenities: ['check_in_area', 'light_bites', 'dj_setup'],
    needs_whole_venue: false,
    catering_rule: 'either',
    vendor_stack: [
      { service_type: 'check_in', necessity: 'recommended', notes: 'Helpful for RSVPs and name tags.' },
      { service_type: 'photographer', necessity: 'optional', notes: 'Capture sponsor and community proof when the organizer wants recap assets.' },
      { service_type: 'catering', necessity: 'recommended', notes: 'Light bites keep guests onsite.' },
      { service_type: 'av_production', necessity: 'conditional', notes: 'Include only when there is a speaker, panel segment, or formal program. Skip for pure networking format.', trigger: { field: 'setup_format', op: 'in', value: ['theater', 'classroom'] } },
      { service_type: 'bartending', necessity: 'optional', notes: 'Use when the host needs bar staffing beyond the venue package.' },
      { service_type: 'security', necessity: 'conditional', notes: 'Needed at the door when headcount exceeds 100.', trigger: { field: 'guest_count', op: 'gte', value: 100 } },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'guest_count', 'date_window', 'ticketed', 'bar_required', 'catering_style', 'photo_video_priority'],
      high_signal: ['check_in_needs', 'indoor_outdoor', 'av_intensity'],
    },
    default_fills: {
      bar_required: true,
      check_in_needs: 'walk_in_list',
      music_format: 'curated_playlist',
      photo_video_priority: 'none',
      catering_style: 'either',
    },
    preferred_commercial_models: ['minimum_spend', 'bar_rev_share', 'per_head'],
    typical_ticket_price_range_cents: [0, 3500],
    typical_minimum_spend_cents: [200000, 800000],
    red_flags: ['Seated-only layouts', 'No bar or beverage program', 'Venue too large for expected turnout'],
  },
  {
    key: 'founder_operator_dinner',
    display_name: 'Founder/operator dinner',
    aliases: [
      'founder dinner', 'founders dinner', 'operator dinner', 'operator supper',
      'executive dinner', 'private founder dinner', 'startup dinner',
      'start up dinner', 'investor dinner', 'operator roundtable',
      'founder roundtable', 'executive supper',
    ],
    adjacent_archetypes: ['private_dinner_celebration', 'panel_fireside', 'networking_mixer'],
    description: 'Intimate private or semi-private dinner for senior operators and founders.',
    preferred_venue_types: ['restaurant', 'private_dining_room', 'restaurant_buyout', 'studio', 'event_space'],
    capacity_range: [12, 40],
    capacity_ratio_min: 1,
    capacity_ratio_max: 1.25,
    required_amenities: ['private_room', 'seated_dining'],
    bonus_amenities: ['wine_program', 'quiet_room', 'host_stand', 'kitchen'],
    needs_whole_venue: false,
    catering_rule: 'kitchen_required',
    vendor_stack: [
      {
        service_type: 'catering',
        necessity: 'conditional',
        notes: 'Include when the venue is a creative or event space without in-house dining. Skip when booking a restaurant or private dining room.',
        trigger: { field: 'catering_style', op: 'neq', value: 'venue_handles' },
      },
      {
        service_type: 'bartending',
        necessity: 'conditional',
        notes: 'Include when the venue does not staff its own bar or the host wants a dedicated bartender or custom wine program.',
        trigger: { field: 'has_bar', op: 'eq', value: true },
      },
      { service_type: 'photographer', necessity: 'optional', notes: 'Add when the dinner has sponsor, investor, or PR content value and the host has confirmed they want photography.' },
      { service_type: 'decor', necessity: 'optional', notes: 'Light room styling for hosted dinners.' },
      { service_type: 'florist', necessity: 'optional', notes: 'Table arrangements for elevated dinners.' },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'guest_count', 'date_window', 'ticketed', 'catering_style', 'bar_required', 'photo_video_priority'],
      high_signal: ['private_or_shared', 'setup_format', 'budget_cap_cents'],
    },
    default_fills: {
      private_or_shared: 'semi_private',
      setup_format: 'seated',
      catering_style: 'venue_handles',
      bar_required: false,
      photo_video_priority: 'none',
    },
    preferred_commercial_models: ['prix_fixe', 'minimum_spend', 'guests_pay_venue'],
    typical_ticket_price_range_cents: [7500, 25000],
    typical_minimum_spend_cents: [150000, 600000],
    red_flags: ['Open dining room without privacy', 'Loud bar environment', 'Unclear prix fixe or minimum-spend terms'],
  },
  {
    key: 'brand_product_launch',
    display_name: 'Brand/product launch',
    aliases: [
      'brand launch', 'product launch', 'launch party', 'press launch',
      'demo launch', 'product showcase', 'launch event', 'launch reception',
      'startup launch', 'start up launch', 'app launch', 'product demo launch',
      'brand showcase', 'press event',
    ],
    adjacent_archetypes: ['pop_up_activation', 'demo_day_pitch_night', 'networking_mixer'],
    description: 'High-visibility launch with demos, photography moments, and sponsor or press needs.',
    preferred_venue_types: ['gallery', 'showroom', 'event_space', 'rooftop'],
    capacity_range: [75, 250],
    capacity_ratio_min: 1.2,
    capacity_ratio_max: 1.8,
    required_amenities: ['demo_stations', 'photo_moments', 'av'],
    bonus_amenities: ['press_wall', 'brandable_space', 'loading_access'],
    needs_whole_venue: true,
    catering_rule: 'outside_ok',
    vendor_stack: [
      { service_type: 'av_production', necessity: 'required', notes: 'Needed for demos, remarks, and media playback.' },
      { service_type: 'photographer', necessity: 'required', notes: 'Launch moments need professional capture.' },
      { service_type: 'videographer', necessity: 'recommended', notes: 'Useful for recap and product content.' },
      { service_type: 'decor', necessity: 'recommended', notes: 'Branding and product staging.' },
      { service_type: 'catering', necessity: 'recommended', notes: 'Passed bites or stations.' },
      { service_type: 'bartending', necessity: 'recommended', notes: 'Bar support for reception pacing.' },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'guest_count', 'date_window', 'ticketed', 'av_intensity', 'photo_video_priority', 'catering_style', 'bar_required'],
      high_signal: ['demo_stations_needed', 'stage_required', 'decor_intensity', 'sponsor_status'],
    },
    default_fills: {
      av_intensity: 'standard',
      photo_video_priority: 'photographer',
      demo_stations_needed: true,
      decor_intensity: 'themed',
      catering_style: 'outside',
      bar_required: true,
    },
    preferred_commercial_models: ['flat_rental', 'sponsor_share', 'ticket_share'],
    typical_ticket_price_range_cents: [0, 7500],
    typical_minimum_spend_cents: [500000, 2000000],
    red_flags: ['No load-in or storage', 'Poor lighting for product photography', 'No AV support for demos'],
  },
  {
    key: 'pop_up_activation',
    display_name: 'Pop-up / activation',
    aliases: [
      'pop up', 'popup', 'pop-up', 'activation', 'brand activation',
      'sampling event', 'market activation', 'retail pop up', 'retail pop-up',
      'pop up shop', 'pop-up shop', 'popup shop', 'pop up market',
      'popup market', 'vendor market', 'retail activation',
    ],
    adjacent_archetypes: ['brand_product_launch', 'community_meetup', 'day_party_brunch_party'],
    description: 'Public-facing retail or brand activation optimized for traffic and sales capture.',
    preferred_venue_types: ['retail', 'gallery', 'cafe', 'market_hall'],
    capacity_range: [50, 500],
    capacity_ratio_min: 2,
    capacity_ratio_max: 3,
    required_amenities: ['foot_traffic', 'load_in', 'storage', 'permits'],
    bonus_amenities: ['street_frontage', 'sampling_area', 'pos'],
    needs_whole_venue: false,
    catering_rule: 'either',
    vendor_stack: [
      { service_type: 'staffing', necessity: 'required', notes: 'Brand staff for guest flow and sampling.' },
      { service_type: 'pos_systems', necessity: 'required', notes: 'Sales and lead capture.' },
      { service_type: 'decor', necessity: 'recommended', notes: 'Retail display and brand buildout.' },
      { service_type: 'permits', necessity: 'conditional', notes: 'Needed for outdoor activations, sampling, or sidewalk usage.', trigger: { field: 'indoor_outdoor', op: 'eq', value: 'outdoor' } },
      { service_type: 'catering', necessity: 'optional', notes: 'Sampling or food service — confirm permit before booking.' },
      { service_type: 'photographer', necessity: 'optional', notes: 'Proof of activation for recap.' },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'date_window', 'guest_count', 'ticketed', 'indoor_outdoor'],
      high_signal: ['demo_stations_needed', 'decor_intensity', 'sponsor_status', 'check_in_needs', 'catering_style'],
    },
    default_fills: {
      guest_count: 100,
      indoor_outdoor: 'indoor',
      demo_stations_needed: true,
      decor_intensity: 'themed',
      check_in_needs: 'walk_in_list',
    },
    preferred_commercial_models: ['flat_rental', 'sponsor_share', 'ticket_share'],
    typical_ticket_price_range_cents: null,
    typical_minimum_spend_cents: [100000, 1000000],
    red_flags: ['No street frontage or foot traffic', 'Weak load-in path', 'No permission for sampling or vending'],
  },
  {
    key: 'workshop_class',
    display_name: 'Workshop / class',
    aliases: [
      'workshop', 'class', 'skill session', 'training', 'hands on session',
      'hands-on session', 'masterclass', 'coding workshop', 'ai workshop',
      'seminar', 'training session', 'hands on workshop', 'hands-on workshop',
      'education session', 'learning session',
    ],
    adjacent_archetypes: ['community_meetup', 'panel_fireside', 'fitness_wellness_run_club'],
    description: 'Teaching-oriented event with tables, screen, Wi-Fi, and a clear instructor flow.',
    preferred_venue_types: ['studio', 'classroom', 'coworking_event_space'],
    capacity_range: [15, 80],
    capacity_ratio_min: 1.1,
    capacity_ratio_max: 1.6,
    required_amenities: ['tables', 'screen', 'wifi'],
    bonus_amenities: ['whiteboard', 'supplies_table', 'quiet_room'],
    needs_whole_venue: false,
    catering_rule: 'either',
    vendor_stack: [
      { service_type: 'instructor', necessity: 'required', notes: 'Lead facilitator or teacher.' },
      { service_type: 'av_production', necessity: 'optional', notes: 'Projection, microphones, and recording support when needed.' },
      { service_type: 'staffing', necessity: 'optional', notes: 'Support check-in and materials.' },
      { service_type: 'catering', necessity: 'optional', notes: 'Coffee, snacks, or lunch.' },
      { service_type: 'check_in', necessity: 'conditional', notes: 'Add when ticketed or paid registration is used.', trigger: { field: 'is_ticketed', op: 'eq', value: true } },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'guest_count', 'date_window', 'setup_format', 'duration_minutes', 'ticketed'],
      high_signal: ['av_intensity', 'screens_count', 'mics_count', 'catering_style', 'budget_cap_cents'],
    },
    default_fills: {
      setup_format: 'theater',
      av_intensity: 'light',
      screens_count: 1,
      mics_count: 1,
      duration_minutes: 120,
      catering_style: 'self',
    },
    preferred_commercial_models: ['flat_rental', 'per_head'],
    typical_ticket_price_range_cents: [2500, 15000],
    typical_minimum_spend_cents: [75000, 400000],
    red_flags: ['No tables or work surfaces', 'Unreliable Wi-Fi', 'No screen for instruction'],
  },
  {
    key: 'panel_fireside',
    display_name: 'Panel / fireside',
    aliases: [
      'panel', 'panle', 'fireside chat', 'fireside', 'speaker panel',
      'talk', 'founder talk', 'speaker event', 'panel discussion',
      'startup panel', 'start up panel', 'start-up panel', 'tech panel',
      'ai panel', 'founder panel', 'operator panel', 'community panel',
      'expert panel', 'speaker talk',
    ],
    adjacent_archetypes: ['workshop_class', 'demo_day_pitch_night', 'networking_mixer'],
    description: 'Seated content program with microphones, sightlines, and networking space.',
    preferred_venue_types: ['coworking_event_space', 'theater', 'auditorium', 'event_space'],
    capacity_range: [50, 200],
    capacity_ratio_min: 1.05,
    capacity_ratio_max: 1.5,
    required_amenities: ['mics', 'seating', 'networking_area'],
    bonus_amenities: ['stage', 'recording', 'green_room'],
    needs_whole_venue: false,
    catering_rule: 'either',
    vendor_stack: [
      { service_type: 'av_production', necessity: 'required', notes: 'Microphones and program audio.' },
      { service_type: 'check_in', necessity: 'recommended', notes: 'Registration and badge flow.' },
      { service_type: 'photographer', necessity: 'optional', notes: 'Speaker and audience capture when recap assets matter.' },
      { service_type: 'videographer', necessity: 'recommended', notes: 'Useful for content reuse and livestream.' },
      { service_type: 'catering', necessity: 'recommended', notes: 'Networking food or drinks.' },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'guest_count', 'date_window', 'ticketed', 'av_intensity', 'mics_count', 'catering_style'],
      high_signal: ['stage_required', 'screens_count', 'photo_video_priority', 'sponsor_status'],
    },
    default_fills: {
      stage_required: true,
      mics_count: 2,
      screens_count: 1,
      av_intensity: 'standard',
      photo_video_priority: 'none',
      catering_style: 'self',
    },
    preferred_commercial_models: ['flat_rental', 'sponsor_share', 'ticket_share'],
    typical_ticket_price_range_cents: [1500, 10000],
    typical_minimum_spend_cents: [150000, 1000000],
    red_flags: ['No microphones', 'Bad sightlines', 'No post-talk networking area'],
  },
  {
    key: 'demo_day_pitch_night',
    display_name: 'Demo day / pitch night',
    aliases: [
      'demo day', 'pitch night', 'startup pitch', 'start up pitch',
      'investor demo', 'pitch event', 'founder showcase', 'startup demo day',
      'start up demo day', 'demo night', 'pitch competition',
      'investor pitch', 'founder pitch night',
    ],
    adjacent_archetypes: ['panel_fireside', 'brand_product_launch', 'networking_mixer'],
    description: 'Startup showcase with stage, investor flow, demos, and sponsor visibility.',
    preferred_venue_types: ['startup_venue', 'auditorium', 'expo_space', 'event_space'],
    capacity_range: [80, 300],
    capacity_ratio_min: 1.2,
    capacity_ratio_max: 1.8,
    required_amenities: ['stage', 'demo_tables', 'investor_flow'],
    bonus_amenities: ['sponsor_booths', 'recording', 'green_room'],
    needs_whole_venue: true,
    catering_rule: 'outside_ok',
    vendor_stack: [
      { service_type: 'av_production', necessity: 'required', notes: 'Stage, microphones, and demo switching.' },
      { service_type: 'check_in', necessity: 'required', notes: 'Investor and founder arrival flow.' },
      { service_type: 'videographer', necessity: 'recommended', notes: 'Pitch recording and recap.' },
      { service_type: 'catering', necessity: 'recommended', notes: 'Networking food and drinks.' },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'guest_count', 'date_window', 'ticketed', 'av_intensity', 'stage_required', 'demo_stations_needed', 'catering_style'],
      high_signal: ['screens_count', 'photo_video_priority', 'sponsor_status'],
    },
    default_fills: {
      stage_required: true,
      demo_stations_needed: true,
      screens_count: 1,
      av_intensity: 'heavy',
      photo_video_priority: 'video',
      sponsor_status: 'sponsored',
    },
    preferred_commercial_models: ['sponsor_share', 'ticket_share', 'flat_rental'],
    typical_ticket_price_range_cents: [0, 15000],
    typical_minimum_spend_cents: [300000, 1500000],
    red_flags: ['No stage or demo tables', 'Weak check-in flow', 'No investor networking area'],
  },
  {
    key: 'hackathon',
    display_name: 'Hackathon',
    aliases: [
      'hackathon', 'hack a thon', 'hack-a-thon',
      'builder weekend', 'code sprint', 'build weekend', 'hack day',
      'code hackathon', 'ai hackathon', 'builder sprint', 'buildathon',
      'build-a-thon',
    ],
    adjacent_archetypes: ['workshop_class', 'demo_day_pitch_night', 'retreat_offsite'],
    description: 'Long-form build event that needs power, Wi-Fi, food, staff, and breakout spaces.',
    preferred_venue_types: ['campus', 'coworking_event_space', 'event_hall'],
    capacity_range: [50, 300],
    capacity_ratio_min: 1.4,
    capacity_ratio_max: 2.2,
    required_amenities: ['power', 'wifi', 'breakout_rooms'],
    bonus_amenities: ['overnight_access', 'quiet_rooms', 'catering_space'],
    needs_whole_venue: true,
    catering_rule: 'outside_ok',
    vendor_stack: [
      { service_type: 'catering', necessity: 'required', notes: 'Meals and snacks are operationally critical.' },
      { service_type: 'av_production', necessity: 'required', notes: 'AV and IT support for demos.' },
      { service_type: 'staffing', necessity: 'required', notes: 'Room management and volunteer coordination.' },
      { service_type: 'security', necessity: 'recommended', notes: 'Needed for long hours or overnight access.' },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'guest_count', 'date_window', 'ticketed', 'duration_days', 'catering_style', 'av_intensity'],
      high_signal: ['screens_count', 'sponsor_status', 'budget_cap_cents'],
    },
    default_fills: {
      duration_days: 1,
      av_intensity: 'standard',
      screens_count: 1,
      catering_style: 'outside',
      sponsor_status: 'sponsored',
    },
    preferred_commercial_models: ['sponsor_covered', 'flat_rental'],
    typical_ticket_price_range_cents: [0, 5000],
    typical_minimum_spend_cents: [500000, 2500000],
    red_flags: ['Weak Wi-Fi', 'Not enough power access', 'No breakout rooms'],
  },
  {
    key: 'community_meetup',
    display_name: 'Community meetup',
    aliases: [
      'community meetup', 'meetup', 'community event', 'club meetup',
      'local meetup', 'community gathering', 'social meetup',
      'local gathering', 'member meetup', 'community night',
      'member gathering', 'group meetup',
    ],
    adjacent_archetypes: ['networking_mixer', 'workshop_class', 'private_dinner_celebration'],
    description: 'Low-friction community gathering with flexible layout and simple economics.',
    preferred_venue_types: ['cafe', 'bar', 'coworking_event_space', 'community_space'],
    capacity_range: [25, 120],
    capacity_ratio_min: 1.1,
    capacity_ratio_max: 1.8,
    required_amenities: ['flexible_layout'],
    bonus_amenities: ['low_minimum', 'easy_check_in', 'light_catering'],
    needs_whole_venue: false,
    catering_rule: 'either',
    vendor_stack: [
      { service_type: 'check_in', necessity: 'optional', notes: 'Useful once attendance is above 75.' },
      { service_type: 'catering', necessity: 'recommended', notes: 'Light food or coffee can improve retention.' },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'guest_count', 'date_window', 'ticketed', 'catering_style'],
      high_signal: ['setup_format', 'mics_count', 'check_in_needs'],
    },
    default_fills: {
      setup_format: 'mixed',
      mics_count: 1,
      catering_style: 'self',
      check_in_needs: 'walk_in_list',
    },
    preferred_commercial_models: ['free_space', 'minimum_spend', 'per_head'],
    typical_ticket_price_range_cents: [0, 2500],
    typical_minimum_spend_cents: [0, 300000],
    red_flags: ['High fixed rental for a casual meetup', 'Rigid seated layout', 'No flexible gathering space'],
  },
  {
    key: 'fundraiser_gala',
    display_name: 'Fundraiser / gala',
    aliases: [
      'fundraiser', 'gala', 'benefit', 'donor reception', 'charity dinner',
      'charity gala', 'benefit dinner', 'fundraiser dinner',
      'donor dinner', 'nonprofit fundraiser', 'non profit fundraiser',
      'charity event', 'donor event',
    ],
    adjacent_archetypes: ['holiday_reception', 'private_dinner_celebration', 'brand_product_launch'],
    description: 'Donation-oriented event with donor flow, sponsor visibility, and polished hospitality.',
    preferred_venue_types: ['ballroom', 'gallery', 'restaurant_buyout', 'event_space'],
    capacity_range: [100, 500],
    capacity_ratio_min: 1.1,
    capacity_ratio_max: 1.7,
    required_amenities: ['donor_flow', 'sponsor_visibility', 'seated_or_reception_space'],
    bonus_amenities: ['auction_area', 'stage', 'coat_check'],
    needs_whole_venue: true,
    catering_rule: 'kitchen_required',
    vendor_stack: [
      { service_type: 'catering', necessity: 'conditional', notes: 'Include when the venue does not provide the gala food package.', trigger: { field: 'catering_style', op: 'neq', value: 'venue_handles' } },
      { service_type: 'bartending', necessity: 'required', notes: 'Bar service and sponsor hospitality.' },
      { service_type: 'av_production', necessity: 'required', notes: 'Program remarks and donor moments.' },
      { service_type: 'decor', necessity: 'recommended', notes: 'Sponsor and gala atmosphere.' },
      { service_type: 'florist', necessity: 'recommended', notes: 'Table and stage floral arrangements are standard for galas.' },
      { service_type: 'photographer', necessity: 'recommended', notes: 'Donor and sponsor recap.' },
      { service_type: 'videographer', necessity: 'optional', notes: 'Highlight reel for future fundraising campaigns.' },
      { service_type: 'check_in', necessity: 'recommended', notes: 'Donor arrival and table management.' },
      { service_type: 'lighting', necessity: 'conditional', notes: 'Production uplighting when the venue is a raw or ballroom space.', trigger: { field: 'venue_type', op: 'in', value: ['ballroom', 'warehouse', 'event_hall', 'event_space'] } },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'guest_count', 'date_window', 'ticketed', 'catering_style', 'bar_required', 'av_intensity', 'photo_video_priority'],
      high_signal: ['stage_required', 'setup_format', 'decor_intensity', 'sponsor_status'],
    },
    default_fills: {
      stage_required: true,
      setup_format: 'seated',
      av_intensity: 'standard',
      decor_intensity: 'full_production',
      catering_style: 'outside',
      bar_required: true,
      photo_video_priority: 'photographer',
      sponsor_status: 'sponsored',
    },
    preferred_commercial_models: ['ticket_share', 'sponsor_share', 'flat_rental'],
    typical_ticket_price_range_cents: [10000, 50000],
    typical_minimum_spend_cents: [1000000, 5000000],
    red_flags: ['No sponsor visibility', 'Weak arrival flow', 'Unclear donation or ticket revenue split'],
  },
  {
    key: 'private_dinner_celebration',
    display_name: 'Private dinner / celebration',
    aliases: [
      'private dinner', 'celebration dinner', 'birthday dinner',
      'anniversary dinner', 'private celebration', 'dinner party',
      'birthday party', 'anniversary party', 'intimate dinner',
      'private supper', 'supper club', 'celebration party',
    ],
    adjacent_archetypes: ['founder_operator_dinner', 'community_meetup', 'holiday_reception'],
    description: 'Private dining or lounge event centered on menu, privacy, and bar fit.',
    preferred_venue_types: ['private_dining_room', 'lounge', 'restaurant', 'restaurant_buyout'],
    capacity_range: [15, 80],
    capacity_ratio_min: 1,
    capacity_ratio_max: 1.35,
    required_amenities: ['privacy', 'menu', 'bar'],
    bonus_amenities: ['cake_service', 'decor_allowed', 'music_allowed'],
    needs_whole_venue: false,
    catering_rule: 'kitchen_required',
    vendor_stack: [
      { service_type: 'cake_pastry', necessity: 'optional', notes: 'Celebration cake or dessert.' },
      {
        service_type: 'catering',
        necessity: 'conditional',
        notes: 'Include when the host is not relying on the venue menu.',
        trigger: { field: 'catering_style', op: 'neq', value: 'venue_handles' },
      },
      {
        service_type: 'bartending',
        necessity: 'conditional',
        notes: 'Include when the host wants a dedicated bar setup or bartender.',
        trigger: { field: 'has_bar', op: 'eq', value: true },
      },
      { service_type: 'decor', necessity: 'recommended', notes: 'Small decor package.' },
      { service_type: 'florist', necessity: 'optional', notes: 'Floral centerpieces for milestone or anniversary dinners.' },
      { service_type: 'photographer', necessity: 'optional', notes: 'Milestone capture.' },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'guest_count', 'date_window', 'ticketed', 'catering_style', 'bar_required', 'photo_video_priority'],
      high_signal: ['private_or_shared', 'setup_format', 'budget_cap_cents'],
    },
    default_fills: {
      private_or_shared: 'private',
      setup_format: 'seated',
      catering_style: 'venue_handles',
      bar_required: false,
      photo_video_priority: 'none',
      music_format: 'none',
    },
    preferred_commercial_models: ['minimum_spend', 'prix_fixe', 'guests_pay_venue'],
    typical_ticket_price_range_cents: null,
    typical_minimum_spend_cents: [150000, 1000000],
    red_flags: ['No privacy', 'Unclear menu minimum', 'Sound restrictions that block the intended vibe'],
  },
  {
    key: 'day_party_brunch_party',
    display_name: 'Day party / brunch party',
    aliases: [
      'day party', 'brunch party', 'rooftop party', 'patio party',
      'sunday party', 'daytime social', 'daytime party', 'brunch event',
      'pool party', '4th of july day party', 'fourth of july day party',
      'july 4 day party', 'july fourth day party', 'holiday day party',
    ],
    adjacent_archetypes: ['networking_mixer', 'nightlife_club_night', 'holiday_reception'],
    description: 'Daytime social with outdoor vibe, bar upside, and sound-limit awareness.',
    preferred_venue_types: ['rooftop', 'bar', 'restaurant_buyout', 'lounge'],
    capacity_range: [75, 250],
    capacity_ratio_min: 1.2,
    capacity_ratio_max: 1.8,
    required_amenities: ['outdoor_vibe', 'bar', 'sound_allowed'],
    bonus_amenities: ['patio', 'dj_setup', 'security_plan'],
    needs_whole_venue: false,
    catering_rule: 'kitchen_required',
    vendor_stack: [
      { service_type: 'dj', necessity: 'required', notes: 'Music sets the party format.' },
      { service_type: 'bartending', necessity: 'optional', notes: 'Bar throughput and menu when venue staffing is not enough.' },
      { service_type: 'security', necessity: 'recommended', notes: 'Useful for large daytime parties.' },
      { service_type: 'photographer', necessity: 'optional', notes: 'Capture social proof.' },
      { service_type: 'catering', necessity: 'optional', notes: 'Brunch food or light bites. Include when the venue does not provide food.' },
      { service_type: 'decor', necessity: 'optional', notes: 'Theme or brunch styling.' },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'guest_count', 'date_window', 'ticketed', 'music_format', 'bar_required', 'catering_style', 'photo_video_priority'],
      high_signal: ['indoor_outdoor', 'security_needs'],
    },
    default_fills: {
      indoor_outdoor: 'outdoor',
      music_format: 'dj',
      bar_required: true,
      security_needs: 'door',
      photo_video_priority: 'photographer',
      catering_style: 'venue_handles',
    },
    preferred_commercial_models: ['bar_rev_share', 'minimum_spend', 'ticket_split'],
    typical_ticket_price_range_cents: [1000, 6000],
    typical_minimum_spend_cents: [500000, 2000000],
    red_flags: ['Strict outdoor sound ordinance', 'Slow bar throughput', 'No rain plan'],
  },
  {
    key: 'nightlife_club_night',
    display_name: 'Nightlife / club night',
    aliases: [
      'nightlife', 'club night', 'dance party', 'late night party',
      'warehouse party', 'nightclub event', 'dj night', 'dj party',
      'afterparty', 'after party', 'late night social', 'dance night',
    ],
    adjacent_archetypes: ['day_party_brunch_party', 'listening_party_showcase', 'networking_mixer'],
    description: 'Late-night music-driven event with door, bar, security, and sound requirements.',
    preferred_venue_types: ['club', 'bar', 'warehouse'],
    capacity_range: [100, 500],
    capacity_ratio_min: 1.2,
    capacity_ratio_max: 1.9,
    required_amenities: ['late_hours', 'sound_system', 'security_plan'],
    bonus_amenities: ['green_room', 'lighting', 'door_area'],
    needs_whole_venue: true,
    catering_rule: 'na',
    vendor_stack: [
      { service_type: 'dj', necessity: 'required', notes: 'DJ or talent is the core draw.' },
      { service_type: 'security', necessity: 'required', notes: 'Door and crowd safety.' },
      { service_type: 'check_in', necessity: 'required', notes: 'Door staff and ticket check.' },
      { service_type: 'lighting', necessity: 'recommended', notes: 'Production value for the room.' },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'guest_count', 'date_window', 'ticketed', 'music_format', 'bar_required', 'security_needs'],
      high_signal: ['lighting_intensity', 'check_in_needs'],
    },
    default_fills: {
      music_format: 'dj',
      lighting_intensity: 'production',
      security_needs: 'full_staff',
      bar_required: true,
      check_in_needs: 'ticket_scan',
      ticketed: true,
    },
    preferred_commercial_models: ['door_split', 'bar_rev_share', 'ticket_share'],
    typical_ticket_price_range_cents: [1500, 8000],
    typical_minimum_spend_cents: [500000, 3000000],
    red_flags: ['No late-hours permit', 'Weak sound system', 'No security staff allowed'],
  },
  {
    key: 'listening_party_showcase',
    display_name: 'Listening party / showcase',
    aliases: [
      'listening party', 'album party', 'music showcase', 'artist showcase',
      'release listening', 'dj listening session', 'listening session',
      'album release', 'release party', 'music event', 'live music showcase',
      'live music event', 'concert', 'live show', 'artist event',
      'band showcase', 'mariachi concert', 'band concert',
    ],
    adjacent_archetypes: ['nightlife_club_night', 'brand_product_launch', 'watch_party_screening'],
    description: 'Music-forward showcase where sound quality, audience flow, and bar or ticket economics matter.',
    preferred_venue_types: ['lounge', 'studio', 'event_space', 'club'],
    capacity_range: [40, 200],
    capacity_ratio_min: 1.1,
    capacity_ratio_max: 1.7,
    required_amenities: ['premium_sound', 'vip_area', 'sound_allowed'],
    bonus_amenities: ['dj_setup', 'green_room', 'lighting'],
    needs_whole_venue: false,
    catering_rule: 'either',
    vendor_stack: [
      { service_type: 'dj', necessity: 'required', notes: 'Audio host, playback, or transitions.' },
      { service_type: 'av_production', necessity: 'required', notes: 'Sound check and room tuning.' },
      { service_type: 'photographer', necessity: 'recommended', notes: 'Artist and audience capture.' },
      { service_type: 'security', necessity: 'optional', notes: 'Useful for VIP or ticketed showcases.' },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'guest_count', 'date_window', 'ticketed', 'av_intensity', 'music_format', 'bar_required', 'photo_video_priority'],
      high_signal: ['setup_format', 'security_needs'],
    },
    default_fills: {
      av_intensity: 'heavy',
      music_format: 'dj',
      setup_format: 'standing',
      photo_video_priority: 'photographer',
      security_needs: 'door',
      bar_required: true,
    },
    preferred_commercial_models: ['flat_rental', 'ticket_split', 'bar_rev_share'],
    typical_ticket_price_range_cents: [1500, 7500],
    typical_minimum_spend_cents: [250000, 1500000],
    red_flags: ['Weak sound system', 'No guest-list control', 'No artist/VIP holding area'],
  },
  {
    key: 'watch_party_screening',
    display_name: 'Watch party / screening',
    aliases: [
      'watch party', 'screening', 'sports watch', 'movie screening',
      'premiere watch', 'viewing party', 'game watch party',
      'playoff watch party', 'sports screening', 'film screening',
      'premiere screening', 'tv screening', 'match viewing party',
    ],
    adjacent_archetypes: ['game_sports_outing', 'community_meetup', 'listening_party_showcase'],
    description: 'Screen-focused gathering where sightlines, sound, and bar or seat economics matter.',
    preferred_venue_types: ['sports_bar', 'theater', 'lounge'],
    capacity_range: [40, 250],
    capacity_ratio_min: 1.1,
    capacity_ratio_max: 1.6,
    required_amenities: ['screens', 'sightlines', 'sound'],
    bonus_amenities: ['reserved_seats', 'bar', 'food_service'],
    needs_whole_venue: false,
    catering_rule: 'either',
    vendor_stack: [
      { service_type: 'av_production', necessity: 'required', notes: 'Screen and sound confirmation — verify projection quality and rights before booking.' },
      { service_type: 'bartending', necessity: 'recommended', notes: 'Bar package or rev-share coordination.' },
      { service_type: 'catering', necessity: 'recommended', notes: 'Food package for longer screenings.' },
      { service_type: 'check_in', necessity: 'optional', notes: 'Ticket or RSVP check.' },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'guest_count', 'date_window', 'ticketed', 'av_intensity', 'screens_count', 'catering_style', 'bar_required'],
      high_signal: ['setup_format'],
    },
    default_fills: {
      screens_count: 1,
      av_intensity: 'standard',
      setup_format: 'theater',
      catering_style: 'venue_handles',
      bar_required: true,
    },
    preferred_commercial_models: ['minimum_spend', 'bar_rev_share', 'ticket_revenue'],
    typical_ticket_price_range_cents: [0, 5000],
    typical_minimum_spend_cents: [150000, 1200000],
    red_flags: ['Blocked sightlines', 'No rights or screening permission', 'Audio cannot support the room'],
  },
  {
    key: 'fitness_wellness_run_club',
    display_name: 'Fitness / wellness / run club',
    aliases: [
      'fitness event', 'wellness event', 'run club', 'yoga class',
      'workout meetup', 'wellness meetup', 'run club brunch',
      'fitness class', 'workout class', 'pilates class', 'yoga event',
      'walk club', 'wellness brunch', 'movement class',
    ],
    adjacent_archetypes: ['community_meetup', 'workshop_class', 'day_party_brunch_party'],
    description: 'Movement or wellness event with route or space needs, check-in, and weather planning.',
    preferred_venue_types: ['studio', 'outdoor_park', 'cafe', 'bar'],
    capacity_range: [20, 150],
    capacity_ratio_min: 1.3,
    capacity_ratio_max: 2.5,
    required_amenities: ['route_or_space', 'rain_plan'],
    bonus_amenities: ['waiver_check_in', 'equipment_storage', 'post_event_food'],
    needs_whole_venue: false,
    catering_rule: 'either',
    vendor_stack: [
      { service_type: 'instructor', necessity: 'required', notes: 'Coach, trainer, or wellness lead.' },
      { service_type: 'check_in', necessity: 'required', notes: 'Waivers and attendance tracking.' },
      { service_type: 'staffing', necessity: 'recommended', notes: 'Route or room support.' },
      { service_type: 'permits', necessity: 'recommended', notes: 'Needed for public outdoor routes or parks.' },
      { service_type: 'catering', necessity: 'optional', notes: 'Post-event food or drinks at a nearby cafe or bar. Florals are not appropriate for this format.' },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'guest_count', 'date_window', 'ticketed', 'indoor_outdoor', 'duration_minutes'],
      high_signal: ['setup_format', 'music_format', 'sponsor_status'],
    },
    default_fills: {
      indoor_outdoor: 'outdoor',
      duration_minutes: 90,
      setup_format: 'hands_on',
      music_format: 'curated_playlist',
    },
    preferred_commercial_models: ['per_head', 'sponsor_share', 'minimum_spend'],
    typical_ticket_price_range_cents: [0, 4000],
    typical_minimum_spend_cents: [50000, 500000],
    red_flags: ['No rain plan', 'No waiver process', 'Route conflicts or park permit uncertainty'],
  },
  {
    key: 'game_sports_outing',
    display_name: 'Game / sports outing',
    aliases: [
      'game outing', 'sports outing', 'game night', 'stadium outing',
      'pregame', 'postgame', 'sports meetup', 'group tickets',
      'baseball game', 'basketball game', 'football game', 'soccer outing',
      'tennis outing', 'tennis match', 'warriors game', 'giants game',
      'stadium game',
    ],
    adjacent_archetypes: ['watch_party_screening', 'community_meetup', 'networking_mixer'],
    description: 'Sports-oriented group event, often with external tickets and a pre/post venue.',
    preferred_venue_types: ['sports_bar', 'bar', 'event_space'],
    capacity_range: [20, 200],
    capacity_ratio_min: 1.1,
    capacity_ratio_max: 1.8,
    required_amenities: ['group_seats_or_screens', 'pre_post_venue'],
    bonus_amenities: ['transport_access', 'reserved_area', 'bar_package'],
    needs_whole_venue: false,
    catering_rule: 'either',
    vendor_stack: [
      { service_type: 'check_in', necessity: 'recommended', notes: 'Group arrival and tickets.' },
      { service_type: 'catering', necessity: 'optional', notes: 'Pre/post food at the venue — confirm whether venue handles or outside catering is allowed.' },
      { service_type: 'transport', necessity: 'optional', notes: 'Helpful for stadium or multi-stop outings.' },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'guest_count', 'date_window', 'ticketed', 'bar_required'],
      high_signal: ['setup_format', 'security_needs', 'catering_style'],
    },
    default_fills: {
      setup_format: 'both',
      ticketed: true,
      bar_required: true,
      security_needs: 'none',
    },
    preferred_commercial_models: ['external_checkout', 'bar_rev_share'],
    typical_ticket_price_range_cents: [3000, 20000],
    typical_minimum_spend_cents: [100000, 1000000],
    red_flags: ['No group ticket path', 'No clear pre/post meetup location', 'Transit or arrival friction'],
  },
  {
    key: 'holiday_reception',
    display_name: 'Holiday reception',
    aliases: [
      'holiday reception', 'holiday party', 'year end party',
      'company holiday event', 'seasonal reception', 'christmas party',
      'xmas party', 'new years reception', 'new year reception',
      'year-end reception', 'company party', 'holiday mixer',
      'seasonal party',
    ],
    adjacent_archetypes: ['networking_mixer', 'private_dinner_celebration', 'fundraiser_gala'],
    description: 'Seasonal reception with food, drinks, music, decor, and tight calendar constraints.',
    preferred_venue_types: ['lounge', 'hotel', 'event_space', 'bar', 'ballroom'],
    capacity_range: [50, 300],
    capacity_ratio_min: 1.1,
    capacity_ratio_max: 1.6,
    required_amenities: ['seasonal_availability', 'bar', 'catering'],
    bonus_amenities: ['photo_booth_space', 'coat_check', 'decor_allowed'],
    needs_whole_venue: false,
    catering_rule: 'kitchen_required',
    vendor_stack: [
      { service_type: 'catering', necessity: 'required', notes: 'Food package for reception.' },
      { service_type: 'bartending', necessity: 'required', notes: 'Bar service or package.' },
      { service_type: 'decor', necessity: 'recommended', notes: 'Seasonal styling.' },
      { service_type: 'florist', necessity: 'optional', notes: 'Floral centrepieces and entrance arrangements.' },
      { service_type: 'photo_booth', necessity: 'optional', notes: 'Common holiday add-on.' },
      { service_type: 'photographer', necessity: 'optional', notes: 'Team and sponsor photos.' },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'guest_count', 'date_window', 'ticketed', 'catering_style', 'bar_required', 'photo_video_priority'],
      high_signal: ['setup_format', 'decor_intensity', 'music_format'],
    },
    default_fills: {
      setup_format: 'reception',
      decor_intensity: 'themed',
      catering_style: 'venue_handles',
      bar_required: true,
      music_format: 'dj',
      photo_video_priority: 'photographer',
    },
    preferred_commercial_models: ['package', 'minimum_spend', 'flat_rental'],
    typical_ticket_price_range_cents: null,
    typical_minimum_spend_cents: [500000, 3000000],
    red_flags: ['Peak-season date unavailable', 'Decor restrictions', 'Food and bar minimums not confirmed'],
  },
  {
    key: 'retreat_offsite',
    display_name: 'Retreat / offsite',
    aliases: [
      'retreat', 'offsite', 'off-site', 'team offsite', 'team off-site',
      'company retreat', 'leadership offsite', 'planning retreat',
      'leadership retreat', 'company offsite', 'company off-site',
      'team planning day', 'team summit',
    ],
    adjacent_archetypes: ['workshop_class', 'founder_operator_dinner', 'hackathon'],
    description: 'Team planning or retreat format requiring privacy, meals, rooms, and activities.',
    preferred_venue_types: ['hotel', 'winery', 'private_estate', 'campus'],
    capacity_range: [15, 100],
    capacity_ratio_min: 1.2,
    capacity_ratio_max: 2,
    required_amenities: ['privacy', 'rooms', 'meals'],
    bonus_amenities: ['breakout_rooms', 'outdoor_space', 'activities'],
    needs_whole_venue: false,
    catering_rule: 'kitchen_required',
    vendor_stack: [
      { service_type: 'staffing', necessity: 'required', notes: 'Facilitation or onsite production support.' },
      { service_type: 'catering', necessity: 'conditional', notes: 'Include when meals are not part of the venue or hotel package.', trigger: { field: 'catering_style', op: 'neq', value: 'venue_handles' } },
      { service_type: 'av_production', necessity: 'recommended', notes: 'Presentation and workshop AV for full-day or multi-day formats.' },
      { service_type: 'transport', necessity: 'recommended', notes: 'Useful for wine country or remote venues.' },
      { service_type: 'decor', necessity: 'optional', notes: 'Light team branding or room setup.' },
    ],
    matching_fields: {
      critical: ['event_type', 'neighborhood', 'guest_count', 'date_window', 'ticketed', 'duration_days', 'catering_style', 'private_or_shared'],
      high_signal: ['setup_format', 'av_intensity', 'sponsor_status', 'budget_cap_cents'],
    },
    default_fills: {
      duration_days: 1,
      setup_format: 'u_shape',
      private_or_shared: 'private',
      catering_style: 'venue_handles',
    },
    preferred_commercial_models: ['package', 'per_head', 'concierge_queue'],
    typical_ticket_price_range_cents: null,
    typical_minimum_spend_cents: [500000, 5000000],
    red_flags: ['No private meeting space', 'Meals not included or unclear', 'Transport complexity hidden until late'],
  },
] satisfies EventArchetypeConfig[]

export const DEFAULT_ARCHETYPE: EventArchetypeConfig =
  ARCHETYPES.find((archetype) => archetype.key === 'private_dinner_celebration') ?? ARCHETYPES[0]
