import type { EventArchetypeConfig } from '@/lib/planner/archetypes/types'

// TODO(archetype-pricing): The source matrix did not include ticket or minimum-spend
// ranges. These defaults are conservative planning ranges and should be reviewed with
// real Bay Area marketplace data after launch.
export const ARCHETYPES = [
  {
    key: 'networking_mixer',
    display_name: 'Networking mixer',
    aliases: ['mixer', 'happy hour', 'networking', 'networking event', 'networking mixer', 'after work drinks', 'cocktail hour'],
    description: 'Standing-room professional social with drinks and light networking.',
    preferred_venue_types: ['bar', 'lounge', 'rooftop', 'coworking_event_space'],
    capacity_range: [40, 150],
    capacity_ratio_min: 1.1,
    capacity_ratio_max: 1.6,
    required_amenities: ['standing_room', 'full_bar'],
    bonus_amenities: ['check_in_area', 'light_bites', 'dj_setup'],
    needs_whole_venue: false,
    catering_rule: 'either',
    vendor_stack: [
      { service_type: 'check_in', necessity: 'recommended', notes: 'Helpful for RSVPs and name tags.' },
      { service_type: 'photographer', necessity: 'recommended', notes: 'Capture sponsor and community proof.' },
      { service_type: 'catering', necessity: 'recommended', notes: 'Light bites keep guests onsite.' },
      { service_type: 'dj', necessity: 'optional', notes: 'Use when the event should feel social after programming.' },
    ],
    preferred_commercial_models: ['minimum_spend', 'bar_rev_share', 'per_head'],
    typical_ticket_price_range_cents: [0, 3500],
    typical_minimum_spend_cents: [200000, 800000],
    red_flags: ['Seated-only layouts', 'No bar or beverage program', 'Venue too large for expected turnout'],
  },
  {
    key: 'founder_operator_dinner',
    display_name: 'Founder/operator dinner',
    aliases: ['founder dinner', 'founders dinner', 'operator dinner', 'operator supper', 'executive dinner', 'private founder dinner'],
    description: 'Intimate private or semi-private dinner for senior operators and founders.',
    preferred_venue_types: ['restaurant', 'private_dining_room', 'restaurant_buyout'],
    capacity_range: [12, 40],
    capacity_ratio_min: 1,
    capacity_ratio_max: 1.25,
    required_amenities: ['private_room', 'seated_dining', 'menu'],
    bonus_amenities: ['wine_program', 'quiet_room', 'host_stand'],
    needs_whole_venue: false,
    catering_rule: 'kitchen_required',
    vendor_stack: [
      { service_type: 'photographer', necessity: 'optional', notes: 'Use only if the dinner has sponsor or content value.' },
    ],
    preferred_commercial_models: ['prix_fixe', 'minimum_spend', 'guests_pay_venue'],
    typical_ticket_price_range_cents: [7500, 25000],
    typical_minimum_spend_cents: [150000, 600000],
    red_flags: ['Open dining room without privacy', 'Loud bar environment', 'Unclear prix fixe or minimum-spend terms'],
  },
  {
    key: 'brand_product_launch',
    display_name: 'Brand/product launch',
    aliases: ['brand launch', 'product launch', 'launch party', 'press launch', 'demo launch', 'product showcase'],
    description: 'High-visibility launch with demos, photography moments, and sponsor or press needs.',
    preferred_venue_types: ['gallery', 'showroom', 'event_space', 'rooftop'],
    capacity_range: [75, 250],
    capacity_ratio_min: 1.2,
    capacity_ratio_max: 1.8,
    required_amenities: ['demo_stations', 'photo_moments', 'av'],
    bonus_amenities: ['press_wall', 'brandable_space', 'loading_access'],
    needs_whole_venue: true,
    catering_rule: 'outside_ok',
    vendor_stack: [
      { service_type: 'av_production', necessity: 'required', notes: 'Needed for demos, remarks, and media playback.' },
      { service_type: 'photographer', necessity: 'required', notes: 'Launch moments need professional capture.' },
      { service_type: 'videographer', necessity: 'recommended', notes: 'Useful for recap and product content.' },
      { service_type: 'decor', necessity: 'recommended', notes: 'Branding and product staging.' },
      { service_type: 'catering', necessity: 'recommended', notes: 'Passed bites or stations.' },
      { service_type: 'bartending', necessity: 'recommended', notes: 'Bar support for reception pacing.' },
    ],
    preferred_commercial_models: ['flat_rental', 'sponsor_share', 'ticket_share'],
    typical_ticket_price_range_cents: [0, 7500],
    typical_minimum_spend_cents: [500000, 2000000],
    red_flags: ['No load-in or storage', 'Poor lighting for product photography', 'No AV support for demos'],
  },
  {
    key: 'pop_up_activation',
    display_name: 'Pop-up / activation',
    aliases: ['pop up', 'popup', 'activation', 'brand activation', 'sampling event', 'market activation', 'retail pop up'],
    description: 'Public-facing retail or brand activation optimized for traffic and sales capture.',
    preferred_venue_types: ['retail', 'gallery', 'cafe', 'market_hall'],
    capacity_range: [50, 500],
    capacity_ratio_min: 2,
    capacity_ratio_max: 3,
    required_amenities: ['foot_traffic', 'load_in', 'storage', 'permits'],
    bonus_amenities: ['street_frontage', 'sampling_area', 'pos'],
    needs_whole_venue: false,
    catering_rule: 'either',
    vendor_stack: [
      { service_type: 'staffing', necessity: 'required', notes: 'Brand staff for guest flow and sampling.' },
      { service_type: 'pos_systems', necessity: 'required', notes: 'Sales and lead capture.' },
      { service_type: 'decor', necessity: 'recommended', notes: 'Retail display and brand buildout.' },
      { service_type: 'permits', necessity: 'recommended', notes: 'Needed when sampling, vending, or using sidewalks.' },
      { service_type: 'photographer', necessity: 'optional', notes: 'Proof of activation for recap.' },
    ],
    preferred_commercial_models: ['flat_rental', 'sponsor_share', 'ticket_share'],
    typical_ticket_price_range_cents: null,
    typical_minimum_spend_cents: [100000, 1000000],
    red_flags: ['No street frontage or foot traffic', 'Weak load-in path', 'No permission for sampling or vending'],
  },
  {
    key: 'workshop_class',
    display_name: 'Workshop / class',
    aliases: ['workshop', 'class', 'skill session', 'training', 'hands on session', 'masterclass'],
    description: 'Teaching-oriented event with tables, screen, Wi-Fi, and a clear instructor flow.',
    preferred_venue_types: ['studio', 'classroom', 'coworking_event_space'],
    capacity_range: [15, 80],
    capacity_ratio_min: 1.1,
    capacity_ratio_max: 1.6,
    required_amenities: ['tables', 'screen', 'wifi'],
    bonus_amenities: ['whiteboard', 'supplies_table', 'quiet_room'],
    needs_whole_venue: false,
    catering_rule: 'either',
    vendor_stack: [
      { service_type: 'instructor', necessity: 'required', notes: 'Lead facilitator or teacher.' },
      { service_type: 'av_production', necessity: 'recommended', notes: 'Projection, microphones, and recording support.' },
      { service_type: 'staffing', necessity: 'optional', notes: 'Support check-in and materials.' },
      { service_type: 'catering', necessity: 'optional', notes: 'Coffee, snacks, or lunch.' },
    ],
    preferred_commercial_models: ['flat_rental', 'per_head'],
    typical_ticket_price_range_cents: [2500, 15000],
    typical_minimum_spend_cents: [75000, 400000],
    red_flags: ['No tables or work surfaces', 'Unreliable Wi-Fi', 'No screen for instruction'],
  },
  {
    key: 'panel_fireside',
    display_name: 'Panel / fireside',
    aliases: ['panel', 'fireside chat', 'speaker panel', 'talk', 'founder talk', 'speaker event'],
    description: 'Seated content program with microphones, sightlines, and networking space.',
    preferred_venue_types: ['coworking_event_space', 'theater', 'auditorium', 'event_space'],
    capacity_range: [50, 200],
    capacity_ratio_min: 1.05,
    capacity_ratio_max: 1.5,
    required_amenities: ['mics', 'seating', 'networking_area'],
    bonus_amenities: ['stage', 'recording', 'green_room'],
    needs_whole_venue: false,
    catering_rule: 'either',
    vendor_stack: [
      { service_type: 'av_production', necessity: 'required', notes: 'Microphones and program audio.' },
      { service_type: 'check_in', necessity: 'recommended', notes: 'Registration and badge flow.' },
      { service_type: 'photographer', necessity: 'recommended', notes: 'Speaker and audience capture.' },
      { service_type: 'videographer', necessity: 'recommended', notes: 'Useful for content reuse.' },
      { service_type: 'catering', necessity: 'recommended', notes: 'Networking food or drinks.' },
    ],
    preferred_commercial_models: ['flat_rental', 'sponsor_share', 'ticket_share'],
    typical_ticket_price_range_cents: [1500, 10000],
    typical_minimum_spend_cents: [150000, 1000000],
    red_flags: ['No microphones', 'Bad sightlines', 'No post-talk networking area'],
  },
  {
    key: 'demo_day_pitch_night',
    display_name: 'Demo day / pitch night',
    aliases: ['demo day', 'pitch night', 'startup pitch', 'investor demo', 'pitch event', 'founder showcase'],
    description: 'Startup showcase with stage, investor flow, demos, and sponsor visibility.',
    preferred_venue_types: ['startup_venue', 'auditorium', 'expo_space', 'event_space'],
    capacity_range: [80, 300],
    capacity_ratio_min: 1.2,
    capacity_ratio_max: 1.8,
    required_amenities: ['stage', 'demo_tables', 'investor_flow'],
    bonus_amenities: ['sponsor_booths', 'recording', 'green_room'],
    needs_whole_venue: true,
    catering_rule: 'outside_ok',
    vendor_stack: [
      { service_type: 'av_production', necessity: 'required', notes: 'Stage, microphones, and demo switching.' },
      { service_type: 'check_in', necessity: 'required', notes: 'Investor and founder arrival flow.' },
      { service_type: 'videographer', necessity: 'recommended', notes: 'Pitch recording and recap.' },
      { service_type: 'catering', necessity: 'recommended', notes: 'Networking food and drinks.' },
    ],
    preferred_commercial_models: ['sponsor_share', 'ticket_share', 'flat_rental'],
    typical_ticket_price_range_cents: [0, 15000],
    typical_minimum_spend_cents: [300000, 1500000],
    red_flags: ['No stage or demo tables', 'Weak check-in flow', 'No investor networking area'],
  },
  {
    key: 'hackathon',
    display_name: 'Hackathon',
    aliases: ['hackathon', 'builder weekend', 'code sprint', 'build weekend', 'hack day'],
    description: 'Long-form build event that needs power, Wi-Fi, food, staff, and breakout spaces.',
    preferred_venue_types: ['campus', 'coworking_event_space', 'event_hall'],
    capacity_range: [50, 300],
    capacity_ratio_min: 1.4,
    capacity_ratio_max: 2.2,
    required_amenities: ['power', 'wifi', 'breakout_rooms'],
    bonus_amenities: ['overnight_access', 'quiet_rooms', 'catering_space'],
    needs_whole_venue: true,
    catering_rule: 'outside_ok',
    vendor_stack: [
      { service_type: 'catering', necessity: 'required', notes: 'Meals and snacks are operationally critical.' },
      { service_type: 'av_production', necessity: 'required', notes: 'AV and IT support for demos.' },
      { service_type: 'staffing', necessity: 'required', notes: 'Room management and volunteer coordination.' },
      { service_type: 'security', necessity: 'recommended', notes: 'Needed for long hours or overnight access.' },
    ],
    preferred_commercial_models: ['sponsor_covered', 'flat_rental'],
    typical_ticket_price_range_cents: [0, 5000],
    typical_minimum_spend_cents: [500000, 2500000],
    red_flags: ['Weak Wi-Fi', 'Not enough power access', 'No breakout rooms'],
  },
  {
    key: 'community_meetup',
    display_name: 'Community meetup',
    aliases: ['community meetup', 'meetup', 'community event', 'club meetup', 'local meetup'],
    description: 'Low-friction community gathering with flexible layout and simple economics.',
    preferred_venue_types: ['cafe', 'bar', 'coworking_event_space', 'community_space'],
    capacity_range: [25, 120],
    capacity_ratio_min: 1.1,
    capacity_ratio_max: 1.8,
    required_amenities: ['flexible_layout'],
    bonus_amenities: ['low_minimum', 'easy_check_in', 'light_catering'],
    needs_whole_venue: false,
    catering_rule: 'either',
    vendor_stack: [
      { service_type: 'check_in', necessity: 'optional', notes: 'Useful once attendance is above 75.' },
      { service_type: 'catering', necessity: 'recommended', notes: 'Light food or coffee can improve retention.' },
    ],
    preferred_commercial_models: ['free_space', 'minimum_spend', 'per_head'],
    typical_ticket_price_range_cents: [0, 2500],
    typical_minimum_spend_cents: [0, 300000],
    red_flags: ['High fixed rental for a casual meetup', 'Rigid seated layout', 'No flexible gathering space'],
  },
  {
    key: 'fundraiser_gala',
    display_name: 'Fundraiser / gala',
    aliases: ['fundraiser', 'gala', 'benefit', 'donor reception', 'charity dinner'],
    description: 'Donation-oriented event with donor flow, sponsor visibility, and polished hospitality.',
    preferred_venue_types: ['ballroom', 'gallery', 'restaurant_buyout', 'event_space'],
    capacity_range: [100, 500],
    capacity_ratio_min: 1.1,
    capacity_ratio_max: 1.7,
    required_amenities: ['donor_flow', 'sponsor_visibility', 'seated_or_reception_space'],
    bonus_amenities: ['auction_area', 'stage', 'coat_check'],
    needs_whole_venue: true,
    catering_rule: 'kitchen_required',
    vendor_stack: [
      { service_type: 'catering', necessity: 'required', notes: 'Food program anchors donor experience.' },
      { service_type: 'bartending', necessity: 'required', notes: 'Bar service and sponsor hospitality.' },
      { service_type: 'av_production', necessity: 'required', notes: 'Program remarks and donor moments.' },
      { service_type: 'decor', necessity: 'recommended', notes: 'Sponsor and gala atmosphere.' },
      { service_type: 'photographer', necessity: 'recommended', notes: 'Donor and sponsor recap.' },
      { service_type: 'check_in', necessity: 'recommended', notes: 'Donor arrival and table management.' },
    ],
    preferred_commercial_models: ['ticket_share', 'sponsor_share', 'flat_rental'],
    typical_ticket_price_range_cents: [10000, 50000],
    typical_minimum_spend_cents: [1000000, 5000000],
    red_flags: ['No sponsor visibility', 'Weak arrival flow', 'Unclear donation or ticket revenue split'],
  },
  {
    key: 'private_dinner_celebration',
    display_name: 'Private dinner / celebration',
    aliases: ['private dinner', 'celebration dinner', 'birthday dinner', 'anniversary dinner', 'private celebration', 'dinner party'],
    description: 'Private dining or lounge event centered on menu, privacy, and bar fit.',
    preferred_venue_types: ['private_dining_room', 'lounge', 'restaurant', 'restaurant_buyout'],
    capacity_range: [15, 80],
    capacity_ratio_min: 1,
    capacity_ratio_max: 1.35,
    required_amenities: ['privacy', 'menu', 'bar'],
    bonus_amenities: ['cake_service', 'decor_allowed', 'music_allowed'],
    needs_whole_venue: false,
    catering_rule: 'kitchen_required',
    vendor_stack: [
      { service_type: 'cake_pastry', necessity: 'optional', notes: 'Celebration cake or dessert.' },
      { service_type: 'decor', necessity: 'recommended', notes: 'Small decor package.' },
      { service_type: 'photographer', necessity: 'optional', notes: 'Milestone capture.' },
      { service_type: 'dj', necessity: 'optional', notes: 'Only for party-oriented dinners.' },
    ],
    preferred_commercial_models: ['minimum_spend', 'prix_fixe', 'guests_pay_venue'],
    typical_ticket_price_range_cents: null,
    typical_minimum_spend_cents: [150000, 1000000],
    red_flags: ['No privacy', 'Unclear menu minimum', 'Sound restrictions that block the intended vibe'],
  },
  {
    key: 'day_party_brunch_party',
    display_name: 'Day party / brunch party',
    aliases: ['day party', 'brunch party', 'rooftop party', 'patio party', 'sunday party', 'daytime social'],
    description: 'Daytime social with outdoor vibe, bar upside, and sound-limit awareness.',
    preferred_venue_types: ['rooftop', 'bar', 'restaurant_buyout', 'lounge'],
    capacity_range: [75, 250],
    capacity_ratio_min: 1.2,
    capacity_ratio_max: 1.8,
    required_amenities: ['outdoor_vibe', 'bar', 'sound_allowed'],
    bonus_amenities: ['patio', 'dj_setup', 'security_plan'],
    needs_whole_venue: false,
    catering_rule: 'kitchen_required',
    vendor_stack: [
      { service_type: 'dj', necessity: 'required', notes: 'Music sets the party format.' },
      { service_type: 'bartending', necessity: 'recommended', notes: 'Bar throughput and menu.' },
      { service_type: 'security', necessity: 'recommended', notes: 'Useful for large daytime parties.' },
      { service_type: 'photographer', necessity: 'optional', notes: 'Capture social proof.' },
      { service_type: 'decor', necessity: 'optional', notes: 'Theme or brunch styling.' },
    ],
    preferred_commercial_models: ['bar_rev_share', 'minimum_spend', 'ticket_split'],
    typical_ticket_price_range_cents: [1000, 6000],
    typical_minimum_spend_cents: [500000, 2000000],
    red_flags: ['Strict outdoor sound ordinance', 'Slow bar throughput', 'No rain plan'],
  },
  {
    key: 'nightlife_club_night',
    display_name: 'Nightlife / club night',
    aliases: ['nightlife', 'club night', 'dance party', 'late night party', 'warehouse party'],
    description: 'Late-night music-driven event with door, bar, security, and sound requirements.',
    preferred_venue_types: ['club', 'bar', 'warehouse'],
    capacity_range: [100, 500],
    capacity_ratio_min: 1.2,
    capacity_ratio_max: 1.9,
    required_amenities: ['late_hours', 'sound_system', 'security_plan'],
    bonus_amenities: ['green_room', 'lighting', 'door_area'],
    needs_whole_venue: true,
    catering_rule: 'na',
    vendor_stack: [
      { service_type: 'dj', necessity: 'required', notes: 'DJ or talent is the core draw.' },
      { service_type: 'security', necessity: 'required', notes: 'Door and crowd safety.' },
      { service_type: 'check_in', necessity: 'required', notes: 'Door staff and ticket check.' },
      { service_type: 'lighting', necessity: 'recommended', notes: 'Production value for the room.' },
    ],
    preferred_commercial_models: ['door_split', 'bar_rev_share', 'ticket_share'],
    typical_ticket_price_range_cents: [1500, 8000],
    typical_minimum_spend_cents: [500000, 3000000],
    red_flags: ['No late-hours permit', 'Weak sound system', 'No security staff allowed'],
  },
  {
    key: 'watch_party_screening',
    display_name: 'Watch party / screening',
    aliases: ['watch party', 'screening', 'sports watch', 'movie screening', 'premiere watch', 'viewing party'],
    description: 'Screen-focused gathering where sightlines, sound, and bar or seat economics matter.',
    preferred_venue_types: ['sports_bar', 'theater', 'lounge'],
    capacity_range: [40, 250],
    capacity_ratio_min: 1.1,
    capacity_ratio_max: 1.6,
    required_amenities: ['screens', 'sightlines', 'sound'],
    bonus_amenities: ['reserved_seats', 'bar', 'food_service'],
    needs_whole_venue: false,
    catering_rule: 'either',
    vendor_stack: [
      { service_type: 'av_production', necessity: 'required', notes: 'Screen and sound confirmation.' },
      { service_type: 'bartending', necessity: 'recommended', notes: 'Bar package or rev-share coordination.' },
      { service_type: 'catering', necessity: 'recommended', notes: 'Food package for longer screenings.' },
      { service_type: 'check_in', necessity: 'optional', notes: 'Ticket or RSVP check.' },
    ],
    preferred_commercial_models: ['minimum_spend', 'bar_rev_share', 'ticket_revenue'],
    typical_ticket_price_range_cents: [0, 5000],
    typical_minimum_spend_cents: [150000, 1200000],
    red_flags: ['Blocked sightlines', 'No rights or screening permission', 'Audio cannot support the room'],
  },
  {
    key: 'fitness_wellness_run_club',
    display_name: 'Fitness / wellness / run club',
    aliases: ['fitness event', 'wellness event', 'run club', 'yoga class', 'workout meetup', 'wellness meetup'],
    description: 'Movement or wellness event with route or space needs, check-in, and weather planning.',
    preferred_venue_types: ['studio', 'outdoor_park', 'cafe', 'bar'],
    capacity_range: [20, 150],
    capacity_ratio_min: 1.3,
    capacity_ratio_max: 2.5,
    required_amenities: ['route_or_space', 'rain_plan'],
    bonus_amenities: ['waiver_check_in', 'equipment_storage', 'post_event_food'],
    needs_whole_venue: false,
    catering_rule: 'either',
    vendor_stack: [
      { service_type: 'instructor', necessity: 'required', notes: 'Coach, trainer, or wellness lead.' },
      { service_type: 'check_in', necessity: 'required', notes: 'Waivers and attendance tracking.' },
      { service_type: 'staffing', necessity: 'recommended', notes: 'Route or room support.' },
      { service_type: 'permits', necessity: 'recommended', notes: 'Needed for public outdoor routes or parks.' },
    ],
    preferred_commercial_models: ['per_head', 'sponsor_share', 'minimum_spend'],
    typical_ticket_price_range_cents: [0, 4000],
    typical_minimum_spend_cents: [50000, 500000],
    red_flags: ['No rain plan', 'No waiver process', 'Route conflicts or park permit uncertainty'],
  },
  {
    key: 'game_sports_outing',
    display_name: 'Game / sports outing',
    aliases: ['game outing', 'sports outing', 'game night', 'stadium outing', 'pregame', 'postgame', 'sports meetup'],
    description: 'Sports-oriented group event, often with external tickets and a pre/post venue.',
    preferred_venue_types: ['sports_bar', 'bar', 'event_space'],
    capacity_range: [20, 200],
    capacity_ratio_min: 1.1,
    capacity_ratio_max: 1.8,
    required_amenities: ['group_seats_or_screens', 'pre_post_venue'],
    bonus_amenities: ['transport_access', 'reserved_area', 'bar_package'],
    needs_whole_venue: false,
    catering_rule: 'either',
    vendor_stack: [
      { service_type: 'check_in', necessity: 'recommended', notes: 'Group arrival and tickets.' },
      { service_type: 'transport', necessity: 'optional', notes: 'Helpful for stadium or multi-stop outings.' },
    ],
    preferred_commercial_models: ['external_checkout', 'bar_rev_share'],
    typical_ticket_price_range_cents: [3000, 20000],
    typical_minimum_spend_cents: [100000, 1000000],
    red_flags: ['No group ticket path', 'No clear pre/post meetup location', 'Transit or arrival friction'],
  },
  {
    key: 'holiday_reception',
    display_name: 'Holiday reception',
    aliases: ['holiday reception', 'holiday party', 'year end party', 'company holiday event', 'seasonal reception'],
    description: 'Seasonal reception with food, drinks, music, decor, and tight calendar constraints.',
    preferred_venue_types: ['lounge', 'hotel', 'event_space', 'bar', 'ballroom'],
    capacity_range: [50, 300],
    capacity_ratio_min: 1.1,
    capacity_ratio_max: 1.6,
    required_amenities: ['seasonal_availability', 'bar', 'catering'],
    bonus_amenities: ['photo_booth_space', 'coat_check', 'decor_allowed'],
    needs_whole_venue: false,
    catering_rule: 'kitchen_required',
    vendor_stack: [
      { service_type: 'catering', necessity: 'required', notes: 'Food package for reception.' },
      { service_type: 'bartending', necessity: 'required', notes: 'Bar service or package.' },
      { service_type: 'dj', necessity: 'recommended', notes: 'Music for reception energy.' },
      { service_type: 'decor', necessity: 'recommended', notes: 'Seasonal styling.' },
      { service_type: 'photo_booth', necessity: 'optional', notes: 'Common holiday add-on.' },
      { service_type: 'photographer', necessity: 'optional', notes: 'Team and sponsor photos.' },
    ],
    preferred_commercial_models: ['package', 'minimum_spend', 'flat_rental'],
    typical_ticket_price_range_cents: null,
    typical_minimum_spend_cents: [500000, 3000000],
    red_flags: ['Peak-season date unavailable', 'Decor restrictions', 'Food and bar minimums not confirmed'],
  },
  {
    key: 'retreat_offsite',
    display_name: 'Retreat / offsite',
    aliases: ['retreat', 'offsite', 'team offsite', 'company retreat', 'leadership offsite'],
    description: 'Team planning or retreat format requiring privacy, meals, rooms, and activities.',
    preferred_venue_types: ['hotel', 'winery', 'private_estate', 'campus'],
    capacity_range: [15, 100],
    capacity_ratio_min: 1.2,
    capacity_ratio_max: 2,
    required_amenities: ['privacy', 'rooms', 'meals'],
    bonus_amenities: ['breakout_rooms', 'outdoor_space', 'activities'],
    needs_whole_venue: false,
    catering_rule: 'kitchen_required',
    vendor_stack: [
      { service_type: 'staffing', necessity: 'required', notes: 'Facilitation or onsite production support.' },
      { service_type: 'catering', necessity: 'required', notes: 'Meals are part of the operating plan.' },
      { service_type: 'transport', necessity: 'recommended', notes: 'Useful for wine country or remote venues.' },
      { service_type: 'decor', necessity: 'optional', notes: 'Light team branding or room setup.' },
    ],
    preferred_commercial_models: ['package', 'per_head', 'concierge_queue'],
    typical_ticket_price_range_cents: null,
    typical_minimum_spend_cents: [500000, 5000000],
    red_flags: ['No private meeting space', 'Meals not included or unclear', 'Transport complexity hidden until late'],
  },
] satisfies EventArchetypeConfig[]

export const DEFAULT_ARCHETYPE: EventArchetypeConfig =
  ARCHETYPES.find((archetype) => archetype.key === 'private_dinner_celebration') ?? ARCHETYPES[0]
