export const mobileSpacing = {
  pagePaddingX: 'px-6',
  pagePaddingTop: 'pt-8',
  pagePaddingBottom: 'pb-12',
  headerPaddingBottom: 'pb-4',
  panelPaddingBottom: 'pb-8',
  sectionGap: 'mt-6',
  sectionGapTight: 'mt-4',
  labelToHeadline: 'mt-3',
  headlineToBody: 'mt-3',
  bodyToAction: 'mt-5',
  cardPadding: 'p-5',
  cardPaddingTight: 'p-4',
  cardPaddingNone: 'p-0',
  cardGap: 'mt-5',
  dividerGap: 'py-4',
  backButtonGap: 'mb-6',
  backButtonGapTight: 'mb-4',
  panelHeaderPadding: 'px-5 py-4',
  rowPadding: 'px-5 py-4',
  compactRowPadding: 'px-4 py-4',
}
