ALTER TABLE public.plans
  ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;

COMMENT ON COLUMN public.plans.metadata IS
  'Planner-owned metadata cache for generated agent summaries, timelines, and execution hints.';

ALTER TABLE public.venue_opportunity_briefs
  ADD COLUMN IF NOT EXISTS approval_status TEXT NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS outreach_message JSONB;

ALTER TABLE public.venue_opportunity_briefs
  DROP CONSTRAINT IF EXISTS venue_opportunity_briefs_approval_status_check;

ALTER TABLE public.venue_opportunity_briefs
  ADD CONSTRAINT venue_opportunity_briefs_approval_status_check
  CHECK (approval_status IN ('pending', 'approved', 'rejected'));

COMMENT ON COLUMN public.venue_opportunity_briefs.approval_status IS
  'Human approval state for generated outreach drafts. Pending means no outreach has been sent.';

COMMENT ON COLUMN public.venue_opportunity_briefs.outreach_message IS
  'Structured approval-ready venue outreach draft generated by the Outreach Agent or deterministic fallback.';

ALTER TABLE public.vendor_opportunity_briefs
  ADD COLUMN IF NOT EXISTS approval_status TEXT NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS outreach_message JSONB;

ALTER TABLE public.vendor_opportunity_briefs
  DROP CONSTRAINT IF EXISTS vendor_opportunity_briefs_approval_status_check;

ALTER TABLE public.vendor_opportunity_briefs
  ADD CONSTRAINT vendor_opportunity_briefs_approval_status_check
  CHECK (approval_status IN ('pending', 'approved', 'rejected'));

COMMENT ON COLUMN public.vendor_opportunity_briefs.approval_status IS
  'Human approval state for generated outreach drafts. Pending means no outreach has been sent.';

COMMENT ON COLUMN public.vendor_opportunity_briefs.outreach_message IS
  'Structured approval-ready vendor outreach draft generated by the Outreach Agent or deterministic fallback.';
