import type { TestInfo } from '@playwright/test'

export const failureTaxonomy = {
  AUTH_ROLE_ACCESS: 'AUTH_ROLE_ACCESS',
  UI_NAVIGATION: 'UI_NAVIGATION',
  UI_STATE_NOT_PERSISTED: 'UI_STATE_NOT_PERSISTED',
  API_500: 'API_500',
  API_CONTRACT_MISMATCH: 'API_CONTRACT_MISMATCH',
  DB_SCHEMA_DRIFT: 'DB_SCHEMA_DRIFT',
  THIRD_PARTY_INTEGRATION: 'THIRD_PARTY_INTEGRATION',
  MISSING_PRODUCT_SURFACE: 'MISSING_PRODUCT_SURFACE',
  DESIGN_REGRESSION: 'DESIGN_REGRESSION',
  CONTRAST_FAILURE: 'CONTRAST_FAILURE',
  MOBILE_LAYOUT_BREAK: 'MOBILE_LAYOUT_BREAK',
  THEME_TOKEN_LEAK: 'THEME_TOKEN_LEAK',
  MONEY_CALCULATION_ERROR: 'MONEY_CALCULATION_ERROR',
  PAYOUT_STATE_ERROR: 'PAYOUT_STATE_ERROR',
  DOUBLE_BOOKING: 'DOUBLE_BOOKING',
  AVAILABILITY_SYNC_FAILURE: 'AVAILABILITY_SYNC_FAILURE',
  DATA_SYNC_FAILURE: 'DATA_SYNC_FAILURE',
  CSV_VALIDATION_ERROR: 'CSV_VALIDATION_ERROR',
  WEBHOOK_FAILURE: 'WEBHOOK_FAILURE',
  INFINITE_LOADING: 'INFINITE_LOADING',
  TEST_DATA_SETUP: 'TEST_DATA_SETUP',
} as const

export type FailureTaxonomy = keyof typeof failureTaxonomy

export function annotateFailure(testInfo: TestInfo, type: FailureTaxonomy, description?: string) {
  testInfo.annotations.push({
    type,
    description: description || failureTaxonomy[type],
  })
}
